# Generated by Django 5.1.7 on 2025-07-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("emoji", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DesignEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_total",
                    models.FloatField(help_text="Área total del terreno en m²"),
                ),
                (
                    "area_basica",
                    models.FloatField(
                        help_text="Área reservada para espacios básicos (50%)"
                    ),
                ),
                (
                    "area_disponible",
                    models.FloatField(help_text="Área restante para opciones"),
                ),
                ("area_usada", models.FloatField(default=0.0)),
                ("porcentaje_ocupado", models.FloatField(default=0.0)),
                (
                    "opciones",
                    models.JSONField(
                        help_text="Opciones seleccionadas con su área y precio"
                    ),
                ),
                ("precio_total", models.FloatField()),
                ("correo", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneralConfig",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_en", models.CharField(max_length=255)),
                ("name_es", models.CharField(max_length=255)),
                ("price_min_usd", models.FloatField()),
                ("area_max_m2", models.FloatField(blank=True, null=True)),
                ("max_units", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="design.category",
                    ),
                ),
            ],
        ),
    ]
