# Generated by Django 5.1.7 on 2025-07-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("design", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price_min_usd",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
