# Generated by Django 5.1.7 on 2025-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("design", "0002_alter_service_price_min_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
    ]
