# Generated by Django 5.2.3 on 2025-07-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del filtro, ej: Habitaciones', max_length=100)),
                ('key', models.CharField(help_text='Clave para la API, ej: bedrooms', max_length=50, unique=True)),
                ('options', models.JSONField(default=list, help_text='Opciones en formato JSON. Ej: [{"label": "1", "params": {"bedrooms": 1}}, {"label": "3+", "params": {"bedrooms__gte": 3}}]')),
            ],
            options={
                'verbose_name': 'Configuración de Filtro',
                'verbose_name_plural': 'Configuraciones de Filtros',
            },
        ),
        migrations.AddField(
            model_name='generalconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
