# Generated by Django 5.2.3 on 2025-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_calculatorentry_delete_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculatorentry',
            old_name='num_pages',
            new_name='area_m2',
        ),
        migrations.RemoveField(
            model_name='calculatorentry',
            name='design_level',
        ),
        migrations.RemoveField(
            model_name='calculatorentry',
            name='has_multilanguage',
        ),
        migrations.AlterField(
            model_name='calculatorentry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
