# Generated by Django 5.2.3 on 2025-07-15 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='home_user',
        ),
    ]
