# Generated by Django 5.2.3 on 2025-07-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userprofile_delete_user_user_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
