# Generated by Django 5.2.4 on 2025-08-08 19:53

import admin_api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='U2 Group', max_length=100)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('like_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('image', models.ImageField(upload_to='marketplace/')),
                ('features', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del proyecto', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Descripción del proyecto', null=True)),
                ('category', models.CharField(help_text='Categoría del proyecto', max_length=100)),
                ('type', models.CharField(help_text='Tipo de proyecto', max_length=100)),
                ('year', models.CharField(help_text='Año del proyecto', max_length=10)),
                ('location', models.CharField(help_text='Ubicación del proyecto', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text='Latitud', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Longitud', max_digits=10, null=True)),
                ('show_on_map', models.BooleanField(default=False, help_text='Mostrar en el mapa')),
                ('status', models.CharField(default='Planning', help_text='Estado del proyecto', max_length=50)),
                ('featured', models.BooleanField(default=False, help_text='Proyecto destacado')),
                ('image', models.ImageField(blank=True, help_text='Imagen del proyecto', null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/extra_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogLikeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(default=admin_api.models.generate_default_visitor_id, max_length=50)),
                ('liked', models.BooleanField(default=False)),
                ('favorited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='admin_api.blog')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('blog', 'visitor_id')},
            },
        ),
        migrations.CreateModel(
            name='ProjectLikeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(default=admin_api.models.generate_default_visitor_id, max_length=50)),
                ('liked', models.BooleanField(default=False)),
                ('favorited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='admin_api.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'visitor_id')},
            },
        ),
    ]
