# Generated by Django 5.2.4 on 2025-08-11 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.CharField(default='5 min', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(default='Blog summary'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Color del proyecto', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.CharField(default='Private House Design', help_text='Servicios del proyecto', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='size',
            field=models.CharField(default='140m2', help_text='Tamaño del proyecto', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='utilization',
            field=models.CharField(default='Private House', help_text='Utilización del proyecto', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Author', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(default='Blog content'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Blog Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(default='General', help_text='Categoría del proyecto', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(default='Proyecto', help_text='Tipo de proyecto', max_length=100),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/extra_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='admin_api.blog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
