# Generated by Django 5.2.4 on 2025-08-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_blog_category_blog_read_time_blog_summary_blog_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(default='Ubicación no especificada', help_text='Ubicación del proyecto', max_length=255),
        ),
    ]
