# Generated by Django 5.2.3 on 2025-01-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_marketplaceproduct_zip_file_cart_marketplaceorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Archivo ZIP del producto', null=True, upload_to='marketplace/zips/'),
        ),
    ]
