# Generated by Django 5.2.4 on 2025-08-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0005_fix_zip_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceproduct',
            name='area_sqft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='area_unit',
            field=models.CharField(default='m2', max_length=10),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='garage_spaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='included_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='main_level_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='not_included_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='price_editable_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='price_editable_sqft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='price_pdf_m2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='marketplaceproduct',
            name='price_pdf_sqft',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='marketplaceproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/'),
        ),
    ]
