# Generated by Django 5.2.4 on 2025-08-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_marketplaceproduct_area_sqft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
