# Generated by Django 5.2.4 on 2025-08-13 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_alter_marketplaceproduct_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketplace/additional_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='admin_api.marketplaceproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
