# Generated by Django 5.2.4 on 2025-08-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplaceorder',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Email del cliente desde el formulario de checkout', max_length=254, null=True),
        ),
    ]
