# Generated by Django 5.2.4 on 2025-08-25 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0010_marketplaceorder_customer_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderZipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Archivo ZIP con los planos y documentos', upload_to='order_zips/')),
                ('filename', models.CharField(help_text='Nombre original del archivo', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to_customer', models.BooleanField(default=False, help_text='Si el archivo fue enviado al cliente')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Fecha de envío al cliente', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_files', to='admin_api.marketplaceorder')),
                ('uploaded_by', models.ForeignKey(help_text='Usuario que subió el archivo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo ZIP de orden',
                'verbose_name_plural': 'Archivos ZIP de órdenes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
