# Generated by Django 5.2.4 on 2025-08-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0011_orderzipfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notas del administrador sobre el mensaje', null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nuevo'), ('read', 'Leído'), ('responded', 'Respondido'), ('archived', 'Archivado')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
