# Generated by Django 5.2.4 on 2025-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0012_contactmessage_admin_notes_contactmessage_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Clave de configuración', max_length=255, unique=True)),
                ('value', models.TextField(help_text='Valor de la configuración')),
                ('description', models.TextField(blank=True, help_text='Descripción de la configuración', null=True)),
                ('category', models.CharField(default='general', help_text='Categoría de la configuración', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
                'ordering': ['category', 'key'],
            },
        ),
    ]
